title: anfela
description: Search Quality Online Stores
timezone: America/Los_Angeles
repository: martyboggs/anfela
permalink: /:categories/:title
excerpt_separator: <!--more-->
# incremental: true
gems:
- jekyll-redirect-from
exclude:
-  notes.txt
collections:
  archive_category:
    permalink: /category/:name
    output: true
  archive_tag:
    permalink: /tag/:name
    output: true
  archive_collection:
    permalink: /all/:name
    output: true
  models:
    output: true
